image: alpine/edge
arch: x86_64
sources:
- git@git.sr.ht:~sungo/dataloader
packages:
- go
- staticcheck

secrets:
- f07f7cff-5ce1-45f3-b34f-5dd66d219b8d

tasks:
- staticcheck: |
    cd dataloader
    staticcheck ./...
- test: |
    cd dataloader
    go test -v ./...
